version: '3.4'
services:
 pg:
  image: postgres:9.6
  environment:
   - POSTGRES_USER
   - POSTGRES_PASSWORD
   - POSTGRES_DB
  logging:
   options:
    max-size: 10m
    max-file: "3"

 webserver:
  image: puckel/docker-airflow:1.10.9
  restart: always
  depends_on:
   - pg
  environment:
   - LOAD_EX
   - EXECUTOR
  logging:
   options:
    max-size: 10m
    max-file: "3"
  volumes:
   - ./dags:/usr/local/airflow/dags
   # - ./plugins:/usr/local/airflow/plugins
  ports:
   - "8080:8080"
  command: webserver
  healthcheck:
   test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
   interval: 30s
   timeout: 30s
   retries: 3
